# Generated by Django 3.2.6 on 2021-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resto_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Review', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
